bots:
  - name: 'test-bot'
    websites:
      - origin: 'https://x.com'
        task_type: 'follows'                  # (not required) task type
        task_title: '【Follows】'             # (not required) task title
        paths: ['hasunosora_SIC']             # (required) users to forward tweets from
        config:
          cron: '*/30 * * * *'
          interval_time:
            max: 0
            min: 0                                 # (required) websites to forward tweets from
      - origin: 'https://x.com'     # (not required) task title
        paths: ['hasunosora_SIC']            # (required) users to forward tweets from
        config:
          cron: '*/2 * * * *'
          interval_time:
            max: 0
            min: 0
    configs:                                  # (not required) forwarder configurations
      user_agent:  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0'                 # (not required) puppeteer supported user agent
      cron: "*/5 4-23 * * *"                   # (not required) cron job
      interval_time:
        max: 15000
        min: 5000
        
