bots:
  - name: '测试机器人'
    websites:                                 # (必须) 需要设置至少一个网页
      - origin: 'https://x.com'               # (必须) 网站域名，注意最后不要有'/'
        # 抓取的用户id，即 https://x.com/userid, 以下示例是莲之空成员的X账号id，可以根据需要修改
        paths: ['hanamiya_nina', 'NozomiNirei', 'sakuraihi_na', 'KonaTsukine', 'kannkannna', 'kurusurindesu', 'ssk_ktk828', 'cocona_nonaka', 'Hayama_Fuka']
        cookie_file: /path/to/day.cookies     # 对应网站的cookies文件，格式为netscape
        config:
          cron: '0-59/10 0-11 * * *'          # 定时任务（见https://crontab.guru/），每10分钟抓取一次，抓取时间为 [0,12) 点之间
      - origin: 'https://x.com'
        paths: ['hanamiya_nina', 'NozomiNirei', 'sakuraihi_na', 'KonaTsukine', 'kannkannna', 'kurusurindesu', 'ssk_ktk828', 'cocona_nonaka', 'Hayama_Fuka']
        cookie_file: /path/to/night.cookies   # 对应网站的cookies文件，格式为netscape
        config:
          cron: '0-59/10 12-22 * * *'
      - origin: 'https://x.com'
        paths: ['hanamiya_nina', 'NozomiNirei', 'sakuraihi_na', 'KonaTsukine','kannkannna', 'kurusurindesu', 'ssk_ktk828', 'cocona_nonaka', 'Hayama_Fuka']
        cookie_file: /path/to/night.cookies
        config:
          cron: '0-59/10 23 * * *'
      - origin: 'https://x.com'
        task_type: 'follows'                  # (可选) 任务类型，follows表示关注者变化，不填写则默认为抓取推文
        task_title: '【莲团声优推特粉丝变化情况】'
        paths: ['hanamiya_nina', 'NozomiNirei', 'ssk_ktk828', 'cocona_nonaka', 'KonaTsukine', 'kannkannna', 'sakuraihi_na', 'Hayama_Fuka', 'kurusurindesu']
        config:                               # (可选) 任务配置，可覆盖全局配置      
          cron: '5 23 * * *'
          interval_time:                      # (可选) 间隔时间，单位毫秒，默认为 {max: 0, min: 0}，在最大最小值之间随机取值
            max: 0
            min: 0
          translator:                         # (可选) 大模型配置，由于转发关注列表并不需要翻译，所以这里设置为none
            type: 'none'
    forward_to:                               # (可选) 转发到多个平台，可以设置多个
      - type: 'telegram'                      # (可选) 转发类型 telegram
        token: 'telegram bot token'           # (必须) telegram 机器人token
        chat_id: 'telegram channel id'        # (必须) telegram 频道id
      - type: 'bilibili'                      # (可选) 转发类型 bilibili
        token: 'SESSDATA in cookies'          # (必须) bilibili cookies里的 SESSDATA
        bili_jct: 'blit_jct in cookies'       # (必须) bilibili cookies里的 bili_jct
      - type: 'qq'                            # (可选) forward type (onebot 11) ref: https://github.com/botuniverse/onebot-11
        token: 'onebot 11 token'              # (必须) onebot 11 token
        group_id: 'qq group id'               # (必须) qq群号
        url: 'onebot server url'              # (必须) onebot 服务器地址
    config:                                   # (可选) 任务配置，可覆盖全局配置
      # 设置user-agent
      user_agent:  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0'                 # (可选) puppeteer supported user agent
      cron: "*/5 4-23 * * *"                  
      interval_time:
        max: 6000
        min: 2000
      media:                                  # (可选) 媒体配置，处理媒体文件
        type: 'no-storage'                    # (可选) 媒体类型，默认为'no-storage'，转发后删除媒体文件
        gallery_dl:                           # (可选) gallery_dl 配置
          path: '<path-to-gallery_dl-executable>'          # (必须) gallery_dl 可执行文件路径
          cookie_file: '/path/to/x.cookies'                # (必须) cookies文件路径
      translator:                             # (可选) 翻译配置，如果需要翻译推文
        type: 'glm-4-flash'                   # (必须) 翻译类型: 'gemini' | 'glm-4-flash' | 'doubao-pro-128k'
        key: 'glm-token'                      # (必须)
  - name: 'all-follows-bot'
    websites:
      - origin: 'https://x.com'
        task_type: 'follows'
        task_title: '【星团声优推特粉丝变化情况】'
        paths: ['SayuriDate', 'Liyu0109', '_Naomi_Payton_', 'AoyamaNagisa', 'MisakiNako_', 'NozomiSuzuhara', 'AyaEmori_BOX', 'a_yabushima', '0927_yuina', 'Sakakura_Sakura']
        config:
          cron: '14 23 * * *'
      - origin: 'https://x.com'
        task_type: 'follows'
        task_title: '【虹团声优推特粉丝变化情况】'
        paths: ['yano_hinaki35', 'aguri_onishi', 'tomori_kusunoki', 'cocohayashi515', 'kaor1n_n', 'MayuSgr',  'kitoakari_1016', 'sashide_m', 't_chiemi1006', 'natyaaaaaaan07', 'iRis_k_miyu', 'k_moeka_', 'uchida_shu0524', 'homoto_akina']
        config:
          cron: '16 23 * * *'
      - origin: 'https://x.com'
        task_type: 'follows'
        task_title: '【水团声优推特粉丝变化情况】'
        paths: ['anju_inami', 'Rikako_Aida', 'suwananaka', 'box_komiyaarisa', 'Saito_Shuka', 'aikyan_', 'Kanako_tktk', 'aina_suzuki723', 'furihata_ai']
        config:
          cron: '24 23 * * *'
      - origin: 'https://x.com'
        task_type: 'follows'
        task_title: '【缪斯声优推特粉丝变化情况】'
        paths: ['nittaemi85', 'nanjolno', 'aya_uchida', 'mimori_suzuko', 'rippialoha', 'pile_eric', 'kusudaaina', 'INFO_shikaco', 'tokui_sorangley']
        config:
          cron: '26 23 * * *'
    forward_to:                        
      - type: 'telegram'               
        token: 'telegram bot token'    
        chat_id: 'telegram channel id' 
      - type: 'bilibili'               
        token: 'SESSDATA in cookies'   
        bili_jct: 'blit_jct in cookies'
      - type: 'qq'                     
        token: 'onebot 11 token'
        group_id: 'qq group id'
        url: 'onebot server url'
    config:
      interval_time:
        max: 0
        min: 0